#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同.
name: Build k2p

on: 
  release:
    types: [published]
  push:
    tags:
       - 'v*'
    branches: 
       - master
#  schedule:
#    - cron: 0 8 * * 5
 # watch:
 #   types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/trihelm/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: K2P-USB-5.0
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config

        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        
        echo "CONFIG_FIRMWARE_INCLUDE_UVC=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_AUDIO=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_LPRD=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_U2EC=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_FTPD=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
        # sudo ./clear_tree
        # sudo ./build_firmware_bkye $TNAME
        # sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
